# Change these first
owner: xnaas
repo: nitter-instances

# Add your sites here
sites:
  - name: nitter.net
    url: https://nitter.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.42l.fr
    url: https://nitter.42l.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.pussthecat.org
    url: https://nitter.pussthecat.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.nixnet.services
    url: https://nitter.nixnet.services
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.fdn.fr
    url: https://nitter.fdn.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.1d4.us
    url: https://nitter.1d4.us
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.kavin.rocks
    url: https://nitter.kavin.rocks
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: nitter.vxempire.xyz
    url: https://nitter.vxempire.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/es.png
  - name: nitter.unixfox.eu
    url: https://nitter.unixfox.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: nitter.domain.glass
    url: https://nitter.domain.glass
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.eu
    url: https://nitter.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fi.png
  - name: nitter.ethibox.fr
    url: https://nitter.ethibox.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.namazso.eu
    url: https://nitter.namazso.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.mailstation.de
    url: https://nitter.mailstation.de
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.actionsack.com
    url: https://nitter.actionsack.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.cattube.org
    url: https://nitter.cattube.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: birdsite.xanny.family
    url: https://birdsite.xanny.family
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/gb.png
  - name: nitter.40two.app
    url: https://nitter.40two.app
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: nitter.skrep.in
    url: https://nitter.skrep.in
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.database.red
    url: https://nitter.database.red
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.exonip.de
    url: https://nitter.exonip.de
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: twitr.gq
    url: https://twitr.gq
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fi.png
  - name: nitter.koyu.space
    url: https://nitter.koyu.space
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.moomoo.me
    url: https://nitter.moomoo.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: bird.trom.tf
    url: https://bird.trom.tf
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.mha.fi
    url: https://nitter.mha.fi
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: xnaas.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /nitter-instances
  logoUrl: https://raw.githubusercontent.com/zedeus/nitter/master/public/favicon-32x32.png
  name: Nitter Instances
  introTitle: "Nitter Instances Uptime"
  introMessage: This status page monitors [Nitter instances](https://github.com/zedeus/nitter/wiki/Instances) for uptime.
  navbar:
    - title: Status
      href: /nitter-instances
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
